sudo: required
language: python 
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
python:
  - "3.6"
os:
  - linux
before_install: 
  - sudo docker swarm init
install: 
  - pip install -r requirements.txt
script: 
  - docker --version
  - python manage.py test
  - /bin/bash push-images.sh
