# Generated by Django 2.0.3 on 2018-04-13 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Promotion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
